version: '3.3'

services:
  reverseproxy:
    image: nginx:alpine
    ports:
      - 1234:80
    restart: always
    volumes:
      - "doc_root:/var/www/html"
      - "./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - wordpress

  wordpress:
    image: wordpress:fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_user_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - "doc_root:/var/www/html"
      - "./php/php.ini:/usr/local/etc/php/php.ini:ro"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_user_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: 
      - "mysql_data:/var/lib/mysql"

volumes:
  doc_root:
  mysql_data: